'use client'

import React, { createContext, useContext, useEffect, useState, useCallback, useMemo } from 'react';

// Supported languages with flags
export const SUPPORTED_LANGUAGES = {
  en: { name: 'English', flag: '🇺🇸', countryCode: 'US' },
  es: { name: 'Español', flag: '🇪🇸', countryCode: 'ES' },
  fr: { name: 'Français', flag: '🇫🇷', countryCode: 'FR' },
  de: { name: 'Deutsch', flag: '🇩🇪', countryCode: 'DE' },
  ro: { name: 'Română', flag: '🇷🇴', countryCode: 'RO' },
  el: { name: 'Ελληνικά', flag: '🇬🇷', countryCode: 'GR' },
  it: { name: 'Italiano', flag: '🇮🇹', countryCode: 'IT' }
};

export type LanguageCode = keyof typeof SUPPORTED_LANGUAGES;

// Country code to language mapping
const COUNTRY_TO_LANGUAGE: Record<string, LanguageCode> = {
  'US': 'en', 'GB': 'en', 'AU': 'en',
  'ES': 'es', 'MX': 'es', 'AR': 'es', 'CO': 'es',
  'FR': 'fr', 'BE': 'fr',
  'DE': 'de', 'AT': 'de', 'LI': 'de',
  'RO': 'ro', 'MD': 'ro',
  'GR': 'el', 'CY': 'el',
  'IT': 'it', 'SM': 'it', 'VA': 'it',
  // Multi-language countries - prioritize based on population/usage
  'CA': 'en', // Canada - English is more common
  'CH': 'de'  // Switzerland - German is most common
};

// Translation object
const translations = {
  en: {
    companyName: "D-PLACK CONSTRUCT",
    companySlogan: "Construction & Rehabilitation",
    pageTitle: "D-PLACK CONSTRUCT - Professional Construction & Rehabilitation Services | Quality Guaranteed",
    pageDescription: "D-PLACK CONSTRUCT: Specialists in construction, demolition, painting, flooring, insulation and electrical and thermal installations. Quality, professionalism and customer satisfaction are our fundamental principles.",
    pageKeywords: "construction, demolition, rehabilitation, painting, flooring, insulation, electrical installations, thermal installations, plaster, tiles, metal structures, foundations, Spain, Madrid, Barcelona, Valencia",
    navEmpresa: "Company",
    navServicios: "Services",
    navGaleria: "Gallery",
    navContacto: "Contact",
    phone: "(0034)-647-857-388",
    ctaPresupuesto: "Request a Quote",
    ctaVerServicios: "View Services",
    heroTitle1: "Construction",
    heroTitle2: "& Rehabilitation",
    heroSubtitle: "Quality, professionalism, and customer appreciation are our core principles. We work with the highest standards of safety and responsibility.",
    featureSeguridad: "Guaranteed Safety",
    featureCalidad: "Premium Quality",
    featureEco: "Eco-Friendly",
    helpText: "Need immediate help?",
    contactanos: "Contact Us",
    contactSubtitle: "Do you have a project in mind? Let's talk! We're here to help make your ideas a reality.",
    infoContacto: "Contact Information",
    telefono: "Phone",
    email: "Email",
    ubicacion: "Location",
    espana: "Spain",
    horario: "Business Hours",
    lunesViernes: "Monday - Friday",
    sabados: "Saturdays",
    domingos: "Sundays",
    cerrado: "Closed",
    enviamosMensaje: "Send Us a Message",
    mensajeExito: "Message sent successfully! We will contact you soon.",
    mensajeError: "There was an error sending the message. Please try again.",
    nombreCompleto: "Full Name *",
    tuNombre: "Your name",
    emailPlaceholder: "your@email.com",
    telefonoPlaceholder: "(0034)-647-857-388",
    servicioInteres: "Service of Interest",
    seleccionaServicio: "Select a service",
    obras: "Construction and Demolition",
    pintura: "Painting and Finishes",
    pavimentos: "Wall and Floor Installation Works",
    aislamiento: "Insulation and Drywall",
    electricas: "Electrical Installations",
    termicas: "Thermal Installations",
    otros: "Other",
    obrasDesc: "Demolitions, plaster, tiles, metal structures, foundations and more.",
    pinturaDesc: "Walls, tiles, wallpaper, interior and exterior painting.",
    pavimentosDesc: "Casting, reinforcement, sandstone, granite, marble, parquet and more.",
    aislamientoDesc: "Drywall, metal structure, insulation and false ceilings.",
    electricasDesc: "Lighting, sockets, switches, projectors and more.",
    termicasDesc: "Heating, radiators, boilers, hydrophores and central systems.",
    mensaje: "Message *",
    mensajePlaceholder: "Tell us about your project...",
    enviando: "Sending...",
    enviarMensaje: "Send Message",
    serviciosHeader: "Our Services",
    serviciosDesc: "We carry out all types of construction work in buildings, annexes, swimming pools, fences, and gates. Exterior and interior finishes, repairs, and more.",
    saberMas: "Learn more",
    verMenos: "Show less",
    serviciosIncluidos: "Included Services:",
    presupuestoPersonalizado: "Need a personalized quote?",
    contactaParaEvaluacion: "Contact us for a free evaluation of your project",
    enlacesRapidos: "Quick Links",
    sobreNosotros: "About Us",
    galeria: "Gallery",
    contacto: "Contact",
    todosProyectos: "All Projects",
    cargando: "Loading",
    verTodosProyectos: "View All Projects",
    footerDerechos: "© 2018 D-PLACK CONSTRUCT. All rights reserved.",
    politicaPrivacidad: "Privacy Policy",
    terminosServicio: "Terms of Service",
    habilitarJS: "You need to enable JavaScript to run this application.",
    // Gallery categories
    categoriaPergolas: "Pergolas",
    categoriaPavimentos: "Flooring",
    categoriaInterior: "Interior",
    categoriaExterior: "Exterior",
    categoriaAislamiento: "Insulation",
    proyecto: "Project",
    proyectoEjemplo: "Sample Project",
    galeriaDesc: "Explore our most outstanding projects and discover the quality of our work.",
    // Gallery pagination and UI
    anterior: "Previous",
    siguiente: "Next",
    imagenNoDisponible: "Image not available",
    // Footer description
    footerDesc: "Specialists in construction, rehabilitation and installations. We work with the highest standards of security, quality and professionalism.",
    // Social media and accessibility
    seguirTwitter: "Follow us on Twitter",
    seguirLinkedIn: "Follow us on LinkedIn",
    politicaPrivacidadLabel: "Privacy Policy",
    terminosServicioLabel: "Terms of Service",
    // Service details translations
    // Construction and Demolition details
    obrasDetalle1: "Plaster rendering",
    obrasDetalle2: "Bare wall (plaster, sandstone, tile, glet, lime, etc.)",
    obrasDetalle3: "Uncovered mosaic",
    obrasDetalle4: "Removed parquet, carpet",
    obrasDetalle5: "Different sand surfaces",
    obrasDetalle6: "Demolition of masonry walls",
    obrasDetalle7: "Demolition of foundations, concrete elements, walls",
    obrasDetalle8: "Dismantling of masonry or brick stoves",
    obrasDetalle9: "Removed metal structures",
    obrasDetalle10: "Dismantled concrete curbs",
    // Painting and Finishes details
    pinturaDetalle1: "Thick glet, repairs, finishing",
    pinturaDetalle2: "Glet finishing",
    pinturaDetalle3: "Grunge glet",
    pinturaDetalle4: "Prepare surfaces for painting",
    pinturaDetalle5: "Washable interior paint (two coats and walls with one color)",
    pinturaDetalle6: "Painted metal structures",
    pinturaDetalle7: "Lacquered and varnished wood joinery",
    pinturaDetalle8: "Zugraveala (glet, slefuit, amorsat, washable)",
    pinturaDetalle9: "Exterior paint (tin, primer, washable)",
    pinturaDetalle10: "PVC / aluminum joint assembly",
    pinturaDetalle11: "Door and window sills",
    pinturaDetalle12: "Stained wood joinery",
    pinturaDetalle13: "Facade prepared for exterior painting",
    pinturaDetalle14: "Applied wallpaper",
    pinturaDetalle15: "Wall panel assembly",
    // Flooring and Wall Installation details
    pavimentosDetalle1: "Concrete leveling screed (thickness function)",
    pavimentosDetalle2: "Excavation preparation",
    pavimentosDetalle3: "Floating screed (concrete)",
    pavimentosDetalle4: "Reinforcement with metal meshes",
    pavimentosDetalle5: "Self-leveling concrete for screed",
    pavimentosDetalle6: "4 cm screed frame including its preparation",
    pavimentosDetalle7: "Granite cladding",
    pavimentosDetalle8: "Stone galvanoplasty (stone function)",
    pavimentosDetalle9: "Assembly of linear elements of marble, granite, travertine, etc.",
    pavimentosDetalle10: "Installation of granite, marble, mosaic window frames, etc.",
    pavimentosDetalle11: "Leveling steps with granite, marble, mosaic, stone, etc.",
    pavimentosDetalle12: "Support layer of agglomerate, OSB, etc.",
    pavimentosDetalle13: "Softwood floor installation",
    pavimentosDetalle14: "Carpet assembly",
    pavimentosDetalle15: "Carpet skirting board assembly",
    pavimentosDetalle16: "Tile assembly (depending on size or model)",
    pavimentosDetalle17: "Sandstone skirting board assembly",
    pavimentosDetalle18: "Stone sandstone tile cladding",
    pavimentosDetalle19: "Marble cladding",
    pavimentosDetalle20: "Mosaic, marble floors",
    pavimentosDetalle21: "Mosaic, marble skirting board placement",
    pavimentosDetalle22: "Mosaic step repair",
    pavimentosDetalle23: "Nevada brick assembly",
    pavimentosDetalle24: "Classic solid wood floor assembly",
    pavimentosDetalle25: "Parquet laying",
    pavimentosDetalle26: "Laminate floor installation",
    pavimentosDetalle27: "MDF, PVC installation",
    pavimentosDetalle28: "Worn wood floors",
    pavimentosDetalle29: "Polished and waxed parquet",
    // Insulation and Drywall details
    aislamientoDetalle1: "Wall cladding with plasterboard on metal structure and insulation",
    aislamientoDetalle2: "Plasterboard wall cladding without metal structure",
    aislamientoDetalle3: "Installation of plasterboard partitions with metal structure per face",
    aislamientoDetalle4: "Plasterboard ceiling placement on metal structure",
    aislamientoDetalle5: "Suspended ceiling installation + wool insulation",
    aislamientoDetalle6: "Scaffold / plasterboard board",
    aislamientoDetalle7: "Mineral wool thermal insulation",
    aislamientoDetalle8: "Various models, arches, scaffolds",
    aislamientoDetalle9: "Painted finishes (mounted tape, cured, polished, primed, washable)",
    aislamientoDetalle10: "False ceiling assembly with polystyrene gluing",
    // Electrical Installations details
    electricasDetalle1: "Complete electrical installation",
    electricasDetalle2: "Lighting accessories",
    electricasDetalle3: "Electrical installation supplement (for each body skirting board)",
    electricasDetalle4: "Assembly of skirting boards, switches, spotlights",
    electricasDetalle5: "Appliance installation",
    // Thermal Installations details
    termicasDetalle1: "Central assembly and connection",
    termicasDetalle2: "Central unit disassembly/assembly without connection",
    termicasDetalle3: "Radiator installation and connection",
    termicasDetalle4: "Radiator removed/assembled without connection",
    termicasDetalle5: "Wood boiler installation",
    termicasDetalle6: "Hydrophore assembly",
    termicasDetalle7: "Water tank assembly",
    termicasDetalle8: "Shower cabin assembly",
    termicasDetalle9: "Classic bathtub installation",
    termicasDetalle10: "Water supply installations",
    termicasDetalle11: "Sewerage systems (assembled pipes). PVC (32, 40, 50 mm)",
    termicasDetalle12: "Water battery changed",
    termicasDetalle13: "Modified copper bathroom installation",
    termicasDetalle14: "Modified pexal bathroom installation",
    termicasDetalle15: "Modified copper kitchen installation",
    termicasDetalle16: "Washing machine connection to sewerage",
    termicasDetalle17: "Sanitary element installation (toilet, sink)",
    termicasDetalle18: "Bathroom and kitchen mounting accessories (supports, mirrors, shelves)",
    termicasDetalle19: "Sanitary element removal"
  },
  es: {
    companyName: "D-PLACK CONSTRUCT",
    companySlogan: "Construcción y Rehabilitación",
    pageTitle: "D-PLACK CONSTRUCT - Construcción y Rehabilitación Profesional | Calidad Garantizada",
    pageDescription: "D-PLACK CONSTRUCT: Especialistas en construcción, demolición, pintura, pavimentos, aislamiento e instalaciones eléctricas y térmicas. Calidad, profesionalidad y satisfacción del cliente son nuestros principios fundamentales.",
    pageKeywords: "construcción, demolición, rehabilitación, pintura, pavimentos, aislamiento, instalaciones eléctricas, instalaciones térmicas, yeso, azulejos, estructuras metálicas, cimientos, España, Madrid, Barcelona, Valencia",
    navEmpresa: "Empresa",
    navServicios: "Servicios",
    navGaleria: "Galería",
    navContacto: "Contacto",
    phone: "(0034)-647-857-388",
    ctaPresupuesto: "Solicitar Presupuesto",
    ctaVerServicios: "Ver Servicios",
    heroTitle1: "Construcción",
    heroTitle2: "y Rehabilitación",
    heroSubtitle: "La calidad, profesionalidad y satisfacción del cliente son nuestros principios fundamentales. Trabajamos con los más altos estándares de seguridad y responsabilidad.",
    featureSeguridad: "Seguridad Garantizada",
    featureCalidad: "Calidad Premium",
    featureEco: "Eco-Friendly",
    helpText: "¿Necesitas ayuda inmediata?",
    contactanos: "Contáctanos",
    contactSubtitle: "¿Tienes un proyecto en mente? ¡Hablemos! Estamos aquí para ayudar a hacer realidad tus ideas.",
    infoContacto: "Información de Contacto",
    telefono: "Teléfono",
    email: "Email",
    ubicacion: "Ubicación",
    espana: "España",
    horario: "Horario de Atención",
    lunesViernes: "Lunes - Viernes",
    sabados: "Sábados",
    domingos: "Domingos",
    cerrado: "Cerrado",
    enviamosMensaje: "Envíanos un Mensaje",
    mensajeExito: "¡Mensaje enviado con éxito! Te contactaremos pronto.",
    mensajeError: "Hubo un error al enviar el mensaje. Por favor, inténtalo de nuevo.",
    nombreCompleto: "Nombre Completo *",
    tuNombre: "Tu nombre",
    emailPlaceholder: "tu@email.com",
    telefonoPlaceholder: "(0034)-647-857-388",
    servicioInteres: "Servicio de Interés",
    seleccionaServicio: "Selecciona un servicio",
    obras: "Construcción y Demolición",
    pintura: "Pintura y Acabados",
    pavimentos: "Obras de Instalación de Paredes y Suelos",
    aislamiento: "Aislamiento y Pladur",
    electricas: "Instalaciones Eléctricas",
    termicas: "Instalaciones Térmicas",
    otros: "Otros",
    obrasDesc: "Demoliciones, yeso, azulejos, estructuras metálicas, cimientos y más.",
    pinturaDesc: "Paredes, azulejos, papel pintado, pintura interior y exterior.",
    pavimentosDesc: "Hormigón, refuerzo, arenisca, granito, mármol, parquet y más.",
    aislamientoDesc: "Pladur, estructura metálica, aislamiento y falsos techos.",
    electricasDesc: "Iluminación, enchufes, interruptores, proyectores y más.",
    termicasDesc: "Calefacción, radiadores, calderas, hidróforos y sistemas centrales.",
    mensaje: "Mensaje *",
    mensajePlaceholder: "Cuéntanos sobre tu proyecto...",
    enviando: "Enviando...",
    enviarMensaje: "Enviar Mensaje",
    serviciosHeader: "Nuestros Servicios",
    serviciosDesc: "Realizamos todo tipo de trabajos de construcción en edificios, anexos, piscinas, vallas y puertas. Acabados exteriores e interiores, reparaciones y más.",
    saberMas: "Saber más",
    verMenos: "Ver menos",
    serviciosIncluidos: "Servicios Incluidos:",
    presupuestoPersonalizado: "¿Necesitas un presupuesto personalizado?",
    contactaParaEvaluacion: "Contáctanos para una evaluación gratuita de tu proyecto",
    enlacesRapidos: "Enlaces Rápidos",
    sobreNosotros: "Sobre Nosotros",
    galeria: "Galería",
    contacto: "Contacto",
    todosProyectos: "Todos los Proyectos",
    cargando: "Cargando",
    verTodosProyectos: "Ver Todos los Proyectos",
    footerDerechos: "© 2018 D-PLACK CONSTRUCT. Todos los derechos reservados.",
    politicaPrivacidad: "Política de Privacidad",
    terminosServicio: "Términos de Servicio",
    habilitarJS: "Necesitas habilitar JavaScript para ejecutar esta aplicación.",
    // Gallery categories
    categoriaPergolas: "Pérgolas",
    categoriaPavimentos: "Pavimentos",
    categoriaInterior: "Interior",
    categoriaExterior: "Exterior",
    categoriaAislamiento: "Aislamiento",
    proyecto: "Proyecto",
    proyectoEjemplo: "Proyecto de ejemplo",
    galeriaDesc: "Explora nuestros proyectos más destacados y descubre la calidad de nuestro trabajo.",
    // Gallery pagination and UI
    anterior: "Anterior",
    siguiente: "Siguiente",
    imagenNoDisponible: "Imagen no disponible",
    // Footer description
    footerDesc: "Especialistas en construcción, rehabilitación e instalaciones. Trabajamos con los más altos criterios de seguridad, calidad y profesionalidad.",
    // Social media and accessibility
    seguirTwitter: "Síguenos en Twitter",
    seguirLinkedIn: "Síguenos en LinkedIn",
    politicaPrivacidadLabel: "Política de Privacidad",
    terminosServicioLabel: "Términos de Servicio",
    // Service details translations
    // Construction and Demolition details
    obrasDetalle1: "Enlucido de yeso",
    obrasDetalle2: "Pared desnuda (yeso, arenisca, azulejo, glet, cal, etc.)",
    obrasDetalle3: "Mosaico descubierto",
    obrasDetalle4: "Parquet removido, alfombra",
    obrasDetalle5: "Superficies de arena diferentes",
    obrasDetalle6: "Demolición de muros de mampostería",
    obrasDetalle7: "Demolición de cimientos, elementos de hormigón, muros",
    obrasDetalle8: "Desmontaje de estufas de mampostería o ladrillo",
    obrasDetalle9: "Estructuras metálicas removidas",
    obrasDetalle10: "Bordillos de hormigón desmontados",
    // Painting and Finishes details
    pinturaDetalle1: "Glet grueso, reparaciones, acabado",
    pinturaDetalle2: "Acabado de glet",
    pinturaDetalle3: "Glet grunge",
    pinturaDetalle4: "Preparar superficies para pintura",
    pinturaDetalle5: "Pintura interior lavable (dos capas y paredes con un color)",
    pinturaDetalle6: "Estructuras metálicas pintadas",
    pinturaDetalle7: "Carpintería de madera lacada y barnizada",
    pinturaDetalle8: "Zugraveala (glet, slefuit, amorsat, lavable)",
    pinturaDetalle9: "Pintura de exterior (estaño, imprimación, lavable)",
    pinturaDetalle10: "Montaje de juntas de PVC / aluminio",
    pinturaDetalle11: "Antepechos de puertas y ventanas",
    pinturaDetalle12: "Carpintería de madera teñida",
    pinturaDetalle13: "Fachada preparada para pintura exterior",
    pinturaDetalle14: "Papel tapiz aplicado",
    pinturaDetalle15: "Montaje de paneles de pared",
    // Flooring and Wall Installation details
    pavimentosDetalle1: "Regla de ecualización de hormigón (función de espesor)",
    pavimentosDetalle2: "Preparación de excavación",
    pavimentosDetalle3: "Flotador flotante (hormigón)",
    pavimentosDetalle4: "Refuerzo con mallas metálicas",
    pavimentosDetalle5: "Hormigón autonivelante para solera",
    pavimentosDetalle6: "Bastidor de 4 cm de solera incluida su preparación",
    pavimentosDetalle7: "Revestimiento de granito",
    pavimentosDetalle8: "Galvanoplastia de piedra (función de piedra)",
    pavimentosDetalle9: "Montaje de elementos lineales de mármol, granito, travertino, etc.",
    pavimentosDetalle10: "Instalación de marcos de ventanas de granito, mármol, mosaico, etc.",
    pavimentosDetalle11: "Pasos de nivelación con granito, mármol, mosaico, piedra, etc.",
    pavimentosDetalle12: "Capa de soporte de aglomerado, OSB, etc.",
    pavimentosDetalle13: "Instalación de pisos de madera blanda",
    pavimentosDetalle14: "Montaje de alfombra",
    pavimentosDetalle15: "Montaje del zócalo de la alfombra",
    pavimentosDetalle16: "Montaje de azulejos (dependiendo del tamaño o modelo)",
    pavimentosDetalle17: "Montaje de zócalo de arenisca",
    pavimentosDetalle18: "Revestimiento de baldosas con piedra arenisca",
    pavimentosDetalle19: "Revestimiento de mármol",
    pavimentosDetalle20: "Suelos de mosaico, mármol",
    pavimentosDetalle21: "Colocación de zócalo de mosaico, mármol",
    pavimentosDetalle22: "Reparación de escalones de mosaico",
    pavimentosDetalle23: "Montaje de ladrillo Nevada",
    pavimentosDetalle24: "Montaje de suelo clásico de madera maciza",
    pavimentosDetalle25: "Tendido de parquet",
    pavimentosDetalle26: "Instalación de pisos laminados",
    pavimentosDetalle27: "Instalación de MDF, PVC",
    pavimentosDetalle28: "Pisos de madera desgastados",
    pavimentosDetalle29: "Parquet pulido y encerado",
    // Insulation and Drywall details
    aislamientoDetalle1: "Enchapado de paredes con placas de yeso en estructura metálica y aislante",
    aislamientoDetalle2: "Enchapado de paredes de cartón yeso sin estructura metálica",
    aislamientoDetalle3: "Instalación de tabiques de placa de yeso con estructura metálica por cara",
    aislamientoDetalle4: "Colocación de techo de pladur en estructura metálica",
    aislamientoDetalle5: "Instalación de techo suspendido + aislamiento de lana",
    aislamientoDetalle6: "Andamio / tablero de yeso",
    aislamientoDetalle7: "Aislamiento térmico de lana mineral",
    aislamientoDetalle8: "Varios modelos, arcadas, andamios",
    aislamientoDetalle9: "Aparejos pintados (banda montada, curado, pulido, imprimado, lavable)",
    aislamientoDetalle10: "Montaje de falsos techos con pegado de poliestireno",
    // Electrical Installations details
    electricasDetalle1: "Instalación eléctrica completa",
    electricasDetalle2: "Accesorios de iluminación",
    electricasDetalle3: "Suplemento de instalación eléctrica (para cada zócalo del cuerpo)",
    electricasDetalle4: "Montaje de zócalos, interruptores, focos",
    electricasDetalle5: "Instalación de electrodomésticos",
    // Thermal Installations details
    termicasDetalle1: "Ensamblaje central y conexión",
    termicasDetalle2: "Desmontaje/ensamblaje del conjunto central sin conexión",
    termicasDetalle3: "Instalación y conexión del radiador",
    termicasDetalle4: "Radiador removido/montado sin conexión",
    termicasDetalle5: "Instalación de calderas de leña",
    termicasDetalle6: "Ensamblaje de hidróforo",
    termicasDetalle7: "Montaje de depósito de agua",
    termicasDetalle8: "Ensamblaje de cabina de ducha",
    termicasDetalle9: "Instalación de bañera clásica",
    termicasDetalle10: "Instalaciones de suministro de agua",
    termicasDetalle11: "Sistemas de alcantarillado (tuberías ensambladas). PVC (32, 40, 50 mm)",
    termicasDetalle12: "Batería de agua cambiada",
    termicasDetalle13: "Instalación de baño modificado en cobre",
    termicasDetalle14: "Instalación de baño pexal modificada",
    termicasDetalle15: "Instalación de cocina modificada en cobre",
    termicasDetalle16: "Conexión de lavadora al alcantarillado",
    termicasDetalle17: "Instalación de elementos sanitarios (inodoro, lavabo)",
    termicasDetalle18: "Accesorios de montaje de baño y cocina (soportes, espejos, estantes)",
    termicasDetalle19: "Remoción de elementos sanitarios"
  },
  fr: {
    companyName: "D-PLACK CONSTRUCT",
    companySlogan: "Construction et Réhabilitation",
    pageTitle: "D-PLACK CONSTRUCT - Construction et Réhabilitation Professionnelle | Qualité Garantie",
    pageDescription: "D-PLACK CONSTRUCT: Spécialistes en construction, démolition, peinture, revêtements de sol, isolation et installations électriques et thermiques. Qualité, professionnalisme et satisfaction client sont nos principes fondamentaux.",
    pageKeywords: "construction, démolition, réhabilitation, peinture, revêtements de sol, isolation, installations électriques, installations thermiques, plâtre, carrelage, structures métalliques, fondations, Espagne, Madrid, Barcelone, Valence",
    navEmpresa: "Entreprise",
    navServicios: "Services",
    navGaleria: "Galerie",
    navContacto: "Contact",
    phone: "(0034)-647-857-388",
    ctaPresupuesto: "Demander un Devis",
    ctaVerServicios: "Voir les Services",
    heroTitle1: "Construction",
    heroTitle2: "et Réhabilitation",
    heroSubtitle: "La qualité, le professionnalisme et la satisfaction client sont nos principes fondamentaux. Nous travaillons avec les plus hauts standards de sécurité et de responsabilité.",
    featureSeguridad: "Sécurité Garantie",
    featureCalidad: "Qualité Premium",
    featureEco: "Éco-Friendly",
    helpText: "Besoin d'aide immédiate?",
    contactanos: "Contactez-nous",
    contactSubtitle: "Vous avez un projet en tête? Parlons-en! Nous sommes là pour vous aider à concrétiser vos idées.",
    infoContacto: "Informations de Contact",
    telefono: "Téléphone",
    email: "Email",
    ubicacion: "Localisation",
    espana: "Espagne",
    horario: "Heures d'Ouverture",
    lunesViernes: "Lundi - Vendredi",
    sabados: "Samedis",
    domingos: "Dimanches",
    cerrado: "Fermé",
    enviamosMensaje: "Envoyez-nous un Message",
    mensajeExito: "Message envoyé avec succès! Nous vous contacterons bientôt.",
    mensajeError: "Il y a eu une erreur lors de l'envoi du message. Veuillez réessayer.",
    nombreCompleto: "Nom Complet *",
    tuNombre: "Votre nom",
    emailPlaceholder: "votre@email.com",
    telefonoPlaceholder: "(0034)-647-857-388",
    servicioInteres: "Service d'Intérêt",
    seleccionaServicio: "Sélectionnez un service",
    obras: "Construction et Démolition",
    pintura: "Peinture et Finitions",
    pavimentos: "Travaux d'Installation de Murs et Sols",
    aislamiento: "Isolation et Plaques de Plâtre",
    electricas: "Installations Électriques",
    termicas: "Installations Thermiques",
    otros: "Autres",
    obrasDesc: "Démolitions, plâtre, carrelage, structures métalliques, fondations et plus.",
    pinturaDesc: "Murs, carrelage, papier peint, peinture intérieure et extérieure.",
    pavimentosDesc: "Béton, renforcement, grès, granit, marbre, parquet et plus.",
    aislamientoDesc: "Plaques de plâtre, structure métallique, isolation et faux plafonds.",
    electricasDesc: "Éclairage, prises, interrupteurs, projecteurs et plus.",
    termicasDesc: "Chauffage, radiateurs, chaudières, hydrophores et systèmes centraux.",
    mensaje: "Message *",
    mensajePlaceholder: "Parlez-nous de votre projet...",
    enviando: "Envoi...",
    enviarMensaje: "Envoyer le Message",
    serviciosHeader: "Nos Services",
    serviciosDesc: "Nous réalisons tous types de travaux de construction dans les bâtiments, annexes, piscines, clôtures et portes. Finitions extérieures et intérieures, réparations et plus.",
    saberMas: "En savoir plus",
    verMenos: "Voir moins",
    serviciosIncluidos: "Services Inclus:",
    presupuestoPersonalizado: "Besoin d'un devis personnalisé?",
    contactaParaEvaluacion: "Contactez-nous pour une évaluation gratuite de votre projet",
    enlacesRapidos: "Liens Rapides",
    sobreNosotros: "À Propos",
    galeria: "Galerie",
    contacto: "Contact",
    todosProyectos: "Tous les Projets",
    cargando: "Chargement",
    verTodosProyectos: "Voir Tous les Projets",
    footerDerechos: "© 2018 D-PLACK CONSTRUCT. Tous droits réservés.",
    politicaPrivacidad: "Politique de Confidentialité",
    terminosServicio: "Conditions de Service",
    habilitarJS: "Vous devez activer JavaScript pour exécuter cette application.",
    // Gallery categories
    categoriaPergolas: "Pergolas",
    categoriaPavimentos: "Revêtements de Sol",
    categoriaInterior: "Intérieur",
    categoriaExterior: "Extérieur",
    categoriaAislamiento: "Isolation",
    proyecto: "Projet",
    proyectoEjemplo: "Projet d'exemple",
    galeriaDesc: "Explorez nos projets les plus remarquables et découvrez la qualité de notre travail.",
    // Gallery pagination and UI
    anterior: "Précédent",
    siguiente: "Suivant",
    imagenNoDisponible: "Image non disponible",
    // Footer description
    footerDesc: "Spécialistes en construction, réhabilitation et installations. Nous travaillons avec les plus hauts standards de sécurité, qualité et professionnalisme.",
    // Social media and accessibility
    seguirTwitter: "Suivez-nous sur Twitter",
    seguirLinkedIn: "Suivez-nous sur LinkedIn",
    politicaPrivacidadLabel: "Politique de Confidentialité",
    terminosServicioLabel: "Conditions de Service",
    // Service details translations
    // Construction and Demolition details
    obrasDetalle1: "Rendu de plâtre",
    obrasDetalle2: "Mur nu (plâtre, grès, carrelage, glet, chaux, etc.)",
    obrasDetalle3: "Mosaïque découverte",
    obrasDetalle4: "Parquet retiré, moquette",
    obrasDetalle5: "Surfaces de sable différentes",
    obrasDetalle6: "Démolition de murs de maçonnerie",
    obrasDetalle7: "Démolition de fondations, éléments en béton, murs",
    obrasDetalle8: "Démontage de poêles en maçonnerie ou brique",
    obrasDetalle9: "Structures métalliques retirées",
    obrasDetalle10: "Bordures en béton démontées",
    // Painting and Finishes details
    pinturaDetalle1: "Glet épais, réparations, finition",
    pinturaDetalle2: "Finition de glet",
    pinturaDetalle3: "Glet grunge",
    pinturaDetalle4: "Préparer les surfaces pour la peinture",
    pinturaDetalle5: "Peinture intérieure lavable (deux couches et murs avec une couleur)",
    pinturaDetalle6: "Structures métalliques peintes",
    pinturaDetalle7: "Menuiserie en bois laquée et vernie",
    pinturaDetalle8: "Zugraveala (glet, slefuit, amorsat, lavable)",
    pinturaDetalle9: "Peinture extérieure (étain, apprêt, lavable)",
    pinturaDetalle10: "Assemblage de joints PVC / aluminium",
    pinturaDetalle11: "Appuis de portes et fenêtres",
    pinturaDetalle12: "Menuiserie en bois teintée",
    pinturaDetalle13: "Façade préparée pour peinture extérieure",
    pinturaDetalle14: "Papier peint appliqué",
    pinturaDetalle15: "Assemblage de panneaux muraux",
    // Flooring and Wall Installation details
    pavimentosDetalle1: "Chape de nivellement en béton (fonction d'épaisseur)",
    pavimentosDetalle2: "Préparation d'excavation",
    pavimentosDetalle3: "Chape flottante (béton)",
    pavimentosDetalle4: "Renforcement avec treillis métalliques",
    pavimentosDetalle5: "Béton autolissant pour chape",
    pavimentosDetalle6: "Cadre de chape de 4 cm incluant sa préparation",
    pavimentosDetalle7: "Revetement de granit",
    pavimentosDetalle8: "Galvanoplastie de pierre (fonction de pierre)",
    pavimentosDetalle9: "Assemblage d'éléments linéaires de marbre, granit, travertin, etc.",
    pavimentosDetalle10: "Installation de cadres de fenêtres en granit, marbre, mosaïque, etc.",
    pavimentosDetalle11: "Pas de nivellement avec granit, marbre, mosaïque, pierre, etc.",
    pavimentosDetalle12: "Couche de support d'aggloméré, OSB, etc.",
    pavimentosDetalle13: "Installation de planchers en bois tendre",
    pavimentosDetalle14: "Assemblage de moquette",
    pavimentosDetalle15: "Assemblage de plinthes de moquette",
    pavimentosDetalle16: "Assemblage de carrelage (selon taille ou modèle)",
    pavimentosDetalle17: "Assemblage de plinthes en grès",
    pavimentosDetalle18: "Revetement de carrelage en pierre grès",
    pavimentosDetalle19: "Revetement de marbre",
    pavimentosDetalle20: "Sols en mosaïque, marbre",
    pavimentosDetalle21: "Pose de plinthes en mosaïque, marbre",
    pavimentosDetalle22: "Réparation de marches en mosaïque",
    pavimentosDetalle23: "Assemblage de brique Nevada",
    pavimentosDetalle24: "Assemblage de sol classique en bois massif",
    pavimentosDetalle25: "Pose de parquet",
    pavimentosDetalle26: "Installation de planchers stratifiés",
    pavimentosDetalle27: "Installation de MDF, PVC",
    pavimentosDetalle28: "Planchers en bois usés",
    pavimentosDetalle29: "Parquet poli et ciré",
    // Insulation and Drywall details
    aislamientoDetalle1: "Revetement mural avec plaques de plâtre sur structure métallique et isolant",
    aislamientoDetalle2: "Revetement mural en carton-plâtre sans structure métallique",
    aislamientoDetalle3: "Installation de cloisons en plaque de plâtre avec structure métallique par face",
    aislamientoDetalle4: "Pose de plafond en pladur sur structure métallique",
    aislamientoDetalle5: "Installation de plafond suspendu + isolation laine",
    aislamientoDetalle6: "Échafaudage / panneau de plâtre",
    aislamientoDetalle7: "Isolation thermique laine minérale",
    aislamientoDetalle8: "Divers modèles, arcades, échafaudages",
    aislamientoDetalle9: "Enduits peints (bande montée, durcie, polie, apprêtée, lavable)",
    aislamientoDetalle10: "Assemblage de faux plafonds avec collage polystyrène",
    // Electrical Installations details
    electricasDetalle1: "Installation électrique complète",
    electricasDetalle2: "Accessoires d'éclairage",
    electricasDetalle3: "Supplément d'installation électrique (pour chaque plinthe de corps)",
    electricasDetalle4: "Assemblage de plinthes, interrupteurs, projecteurs",
    electricasDetalle5: "Installation d'électroménagers",
    // Thermal Installations details
    termicasDetalle1: "Assemblage central et connexion",
    termicasDetalle2: "Démontage/assemblage de l'ensemble central sans connexion",
    termicasDetalle3: "Installation et connexion du radiateur",
    termicasDetalle4: "Radiateur retiré/assemblé sans connexion",
    termicasDetalle5: "Installation de chaudières à bois",
    termicasDetalle6: "Assemblage d'hydrophore",
    termicasDetalle7: "Assemblage de réservoir d'eau",
    termicasDetalle8: "Assemblage de cabine de douche",
    termicasDetalle9: "Installation de baignoire classique",
    termicasDetalle10: "Installations d'alimentation en eau",
    termicasDetalle11: "Systèmes d'assainissement (tuyaux assemblés). PVC (32, 40, 50 mm)",
    termicasDetalle12: "Batterie d'eau changée",
    termicasDetalle13: "Installation de salle de bain modifiée en cuivre",
    termicasDetalle14: "Installation de salle de bain pexal modifiée",
    termicasDetalle15: "Installation de cuisine modifiée en cuivre",
    termicasDetalle16: "Connexion de machine à laver à l'assainissement",
    termicasDetalle17: "Installation d'éléments sanitaires (toilettes, lavabo)",
    termicasDetalle18: "Accessoires de montage salle de bain et cuisine (supports, miroirs, étagères)",
    termicasDetalle19: "Retrait d'éléments sanitaires"
  },
  de: {
    companyName: "D-PLACK CONSTRUCT",
    companySlogan: "Bau und Sanierung",
    pageTitle: "D-PLACK CONSTRUCT - Professioneller Bau und Sanierung | Qualität Garantiert",
    pageDescription: "D-PLACK CONSTRUCT: Spezialisten für Bau, Abbruch, Malerei, Bodenbeläge, Dämmung sowie elektrische und thermische Installationen. Qualität, Professionalität und Kundenzufriedenheit sind unsere Grundprinzipien.",
    pageKeywords: "Bau, Abbruch, Sanierung, Malerei, Bodenbeläge, Dämmung, Elektroinstallationen, Heizungsinstallationen, Putz, Fliesen, Metallkonstruktionen, Fundamente, Spanien, Madrid, Barcelona, Valencia",
    navEmpresa: "Unternehmen",
    navServicios: "Dienstleistungen",
    navGaleria: "Galerie",
    navContacto: "Kontakt",
    phone: "(0034)-647-857-388",
    ctaPresupuesto: "Angebot anfordern",
    ctaVerServicios: "Dienstleistungen anzeigen",
    heroTitle1: "Bau",
    heroTitle2: "und Sanierung",
    heroSubtitle: "Qualität, Professionalität und Kundenzufriedenheit sind unsere Grundprinzipien. Wir arbeiten mit den höchsten Sicherheits- und Verantwortungsstandards.",
    featureSeguridad: "Garantierte Sicherheit",
    featureCalidad: "Premium Qualität",
    featureEco: "Umweltfreundlich",
    helpText: "Sofortige Hilfe benötigt?",
    contactanos: "Kontaktieren Sie uns",
    contactSubtitle: "Haben Sie ein Projekt im Sinn? Lassen Sie uns reden! Wir sind hier, um Ihnen zu helfen, Ihre Ideen zu verwirklichen.",
    infoContacto: "Kontaktinformationen",
    telefono: "Telefon",
    email: "E-Mail",
    ubicacion: "Standort",
    espana: "Spanien",
    horario: "Geschäftszeiten",
    lunesViernes: "Montag - Freitag",
    sabados: "Samstage",
    domingos: "Sonntage",
    cerrado: "Geschlossen",
    enviamosMensaje: "Senden Sie uns eine Nachricht",
    mensajeExito: "Nachricht erfolgreich gesendet! Wir werden Sie bald kontaktieren.",
    mensajeError: "Beim Senden der Nachricht ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    nombreCompleto: "Vollständiger Name *",
    tuNombre: "Ihr Name",
    emailPlaceholder: "ihre@email.com",
    telefonoPlaceholder: "(0034)-647-857-388",
    servicioInteres: "Interessierter Service",
    seleccionaServicio: "Wählen Sie einen Service",
    obras: "Bau und Abbruch",
    pintura: "Malerarbeiten und Fertigstellung",
    pavimentos: "Wand- und Bodeninstallationsarbeiten",
    aislamiento: "Dämmung und Trockenbau",
    electricas: "Elektroinstallationen",
    termicas: "Thermische Installationen",
    otros: "Andere",
    obrasDesc: "Abbrucharbeiten, Putz, Fliesen, Metallkonstruktionen, Fundamente und mehr.",
    pinturaDesc: "Wände, Fliesen, Tapeten, Innen- und Außenanstrich.",
    pavimentosDesc: "Beton, Bewehrung, Sandstein, Granit, Marmor, Parkett und mehr.",
    aislamientoDesc: "Trockenbau, Metallkonstruktion, Dämmung und abgehängte Decken.",
    electricasDesc: "Beleuchtung, Steckdosen, Schalter, Projektoren und mehr.",
    termicasDesc: "Heizung, Heizkörper, Kessel, Hydrophore und Zentralanlagen.",
    mensaje: "Nachricht *",
    mensajePlaceholder: "Erzählen Sie uns von Ihrem Projekt...",
    enviando: "Senden...",
    enviarMensaje: "Nachricht senden",
    serviciosHeader: "Unsere Dienstleistungen",
    serviciosDesc: "Wir führen alle Arten von Bauarbeiten in Gebäuden, Nebengebäuden, Schwimmbädern, Zäunen und Toren durch. Außen- und Innenausbau, Reparaturen und mehr.",
    saberMas: "Mehr erfahren",
    verMenos: "Weniger anzeigen",
    serviciosIncluidos: "Eingeschlossene Dienstleistungen:",
    presupuestoPersonalizado: "Benötigen Sie ein personalisiertes Angebot?",
    contactaParaEvaluacion: "Kontaktieren Sie uns für eine kostenlose Bewertung Ihres Projekts",
    enlacesRapidos: "Schnelllinks",
    sobreNosotros: "Über uns",
    galeria: "Galerie",
    contacto: "Kontakt",
    todosProyectos: "Alle Projekte",
    cargando: "Laden",
    verTodosProyectos: "Alle Projekte anzeigen",
    footerDerechos: "© 2018 D-PLACK CONSTRUCT. Alle Rechte vorbehalten.",
    politicaPrivacidad: "Datenschutzrichtlinie",
    terminosServicio: "Nutzungsbedingungen",
    habilitarJS: "Sie müssen JavaScript aktivieren, um diese Anwendung auszuführen.",
    // Gallery categories
    categoriaPergolas: "Pergolen",
    categoriaPavimentos: "Bodenbeläge",
    categoriaInterior: "Innenausbau",
    categoriaExterior: "Außenausbau",
    categoriaAislamiento: "Dämmung",
    proyecto: "Projekt",
    proyectoEjemplo: "Beispielprojekt",
    galeriaDesc: "Entdecken Sie unsere herausragendsten Projekte und erleben Sie die Qualität unserer Arbeit.",
    // Gallery pagination and UI
    anterior: "Zurück",
    siguiente: "Weiter",
    imagenNoDisponible: "Bild nicht verfügbar",
    // Footer description
    footerDesc: "Spezialisten für Bau, Sanierung und Installationen. Wir arbeiten mit den höchsten Standards für Sicherheit, Qualität und Professionalität.",
    // Social media and accessibility
    seguirTwitter: "Folgen Sie uns auf Twitter",
    seguirLinkedIn: "Folgen Sie uns auf LinkedIn",
    politicaPrivacidadLabel: "Datenschutzrichtlinie",
    terminosServicioLabel: "Nutzungsbedingungen",
    // Service details translations - German
    obrasDetalle1: "Gipsputz",
    obrasDetalle2: "Nackte Wand (Gips, Sandstein, Fliese, Glet, Kalk, etc.)",
    obrasDetalle3: "Unbedecktes Mosaik",
    obrasDetalle4: "Entferntes Parkett, Teppich",
    obrasDetalle5: "Verschiedene Sandoberflächen",
    obrasDetalle6: "Abriss von Mauerwerkswänden",
    obrasDetalle7: "Abriss von Fundamenten, Betonelementen, Wänden",
    obrasDetalle8: "Demontage von Mauerwerk- oder Ziegelöfen",
    obrasDetalle9: "Entfernte Metallstrukturen",
    obrasDetalle10: "Demontierte Betonkanten",
    pinturaDetalle1: "Dicker Glet, Reparaturen, Finish",
    pinturaDetalle2: "Glet-Finish",
    pinturaDetalle3: "Grunge Glet",
    pinturaDetalle4: "Oberflächen für Malerei vorbereiten",
    pinturaDetalle5: "Waschbare Innenfarbe (zwei Schichten und Wände mit einer Farbe)",
    pinturaDetalle6: "Gestrichene Metallstrukturen",
    pinturaDetalle7: "Lackierte und lackierte Holztischlerei",
    pinturaDetalle8: "Zugraveala (Glet, Slefuit, Amorsat, waschbar)",
    pinturaDetalle9: "Außenfarbe (Zinn, Grundierung, waschbar)",
    pinturaDetalle10: "PVC / Aluminium-Fugenmontage",
    pinturaDetalle11: "Tür- und Fensterbänke",
    pinturaDetalle12: "Getönte Holztischlerei",
    pinturaDetalle13: "Fassade für Außenanstrich vorbereitet",
    pinturaDetalle14: "Aufgetapete Tapete",
    pinturaDetalle15: "Wandpaneelmontage",
    pavimentosDetalle1: "Betonausgleichsestrich (Dickenfunktion)",
    pavimentosDetalle2: "Aushubvorbereitung",
    pavimentosDetalle3: "Schwimmender Estrich (Beton)",
    pavimentosDetalle4: "Verstärkung mit Metallgittern",
    pavimentosDetalle5: "Selbstnivellierender Beton für Estrich",
    pavimentosDetalle6: "4 cm Estrichrahmen einschließlich Vorbereitung",
    pavimentosDetalle7: "Granitverkleidung",
    pavimentosDetalle8: "Steingalvanoplastik (Steinfunktion)",
    pavimentosDetalle9: "Montage linearer Elemente aus Marmor, Granit, Travertin, etc.",
    pavimentosDetalle10: "Installation von Granit-, Marmor-, Mosaikfensterrahmen, etc.",
    pavimentosDetalle11: "Nivellierungsschritte mit Granit, Marmor, Mosaik, Stein, etc.",
    pavimentosDetalle12: "Trägerschicht aus Spanplatten, OSB, etc.",
    pavimentosDetalle13: "Weichholzbodeninstallation",
    pavimentosDetalle14: "Teppichmontage",
    pavimentosDetalle15: "Teppichsockelleistenmontage",
    pavimentosDetalle16: "Fliesenmontage (je nach Größe oder Modell)",
    pavimentosDetalle17: "Sandsteinsockelleistenmontage",
    pavimentosDetalle18: "Steinsandsteinfliesenverkleidung",
    pavimentosDetalle19: "Marmorverkleidung",
    pavimentosDetalle20: "Mosaik-, Marmorböden",
    pavimentosDetalle21: "Mosaik-, Marmorsockelleistenplatzierung",
    pavimentosDetalle22: "Mosaikstufenreparatur",
    pavimentosDetalle23: "Nevada-Ziegelmontage",
    pavimentosDetalle24: "Klassische Massivholzbodenmontage",
    pavimentosDetalle25: "Parkettverlegung",
    pavimentosDetalle26: "Laminatbodeninstallation",
    pavimentosDetalle27: "MDF-, PVC-Installation",
    pavimentosDetalle28: "Abgenutzte Holzböden",
    pavimentosDetalle29: "Poliertes und gewachstes Parkett",
    aislamientoDetalle1: "Wandverkleidung mit Gipskartonplatten auf Metallstruktur und Dämmung",
    aislamientoDetalle2: "Gipskartonwandverkleidung ohne Metallstruktur",
    aislamientoDetalle3: "Installation von Gipskarton-Trennwänden mit Metallstruktur pro Seite",
    aislamientoDetalle4: "Pladur-Deckenplatzierung auf Metallstruktur",
    aislamientoDetalle5: "Abgehängte Deckeninstallation + Wolldämmung",
    aislamientoDetalle6: "Gerüst / Gipsplatte",
    aislamientoDetalle7: "Mineralwolle-Wärmedämmung",
    aislamientoDetalle8: "Verschiedene Modelle, Arkaden, Gerüste",
    aislamientoDetalle9: "Gestrichene Putze (montiertes Band, ausgehärtet, poliert, grundiert, waschbar)",
    aislamientoDetalle10: "Falsche Deckenmontage mit Polystyrolklebung",
    electricasDetalle1: "Vollständige Elektroinstallation",
    electricasDetalle2: "Beleuchtungszubehör",
    electricasDetalle3: "Elektroinstallationszuschlag (für jede Körpersockelleiste)",
    electricasDetalle4: "Montage von Sockelleisten, Schaltern, Spots",
    electricasDetalle5: "Geräteinstallation",
    termicasDetalle1: "Zentralmontage und -anschluss",
    termicasDetalle2: "Zentralgerätedemontage/-montage ohne Anschluss",
    termicasDetalle3: "Heizkörperinstallation und -anschluss",
    termicasDetalle4: "Heizkörper entfernt/montiert ohne Anschluss",
    termicasDetalle5: "Holzkesselinstallation",
    termicasDetalle6: "Hydrophor-Montage",
    termicasDetalle7: "Wassertankmontage",
    termicasDetalle8: "Duschkabinenmontage",
    termicasDetalle9: "Klassische Badewanneninstallation",
    termicasDetalle10: "Wasserversorgungsanlagen",
    termicasDetalle11: "Abwassersysteme (montierte Rohre). PVC (32, 40, 50 mm)",
    termicasDetalle12: "Wasserbatterie gewechselt",
    termicasDetalle13: "Modifizierte Kupferbadezimmerinstallation",
    termicasDetalle14: "Modifizierte Pexal-Badezimmerinstallation",
    termicasDetalle15: "Modifizierte Kupferkücheninstallation",
    termicasDetalle16: "Waschmaschinenanschluss an Abwasser",
    termicasDetalle17: "Sanitärelementinstallation (Toilette, Waschbecken)",
    termicasDetalle18: "Badezimmer- und Küchenmontagezubehör (Halterungen, Spiegel, Regale)",
    termicasDetalle19: "Sanitärelemententfernung"
  },
  ro: {
    companyName: "D-PLACK CONSTRUCT",
    companySlogan: "Construcție și Reabilitare",
    navEmpresa: "Companie",
    navServicios: "Servicii",
    navGaleria: "Galerie",
    navContacto: "Contact",
    phone: "(0034)-647-857-388",
    ctaPresupuesto: "Solicită Ofertă",
    ctaVerServicios: "Vezi Serviciile",
    heroTitle1: "Construcție",
    heroTitle2: "și Reabilitare",
    heroSubtitle: "Calitatea, profesionalismul și satisfacția clientului sunt principiile noastre fundamentale. Lucrăm cu cele mai înalte standarde de siguranță și responsabilitate.",
    featureSeguridad: "Siguranță Garantată",
    featureCalidad: "Calitate Premium",
    featureEco: "Eco-Friendly",
    helpText: "Ai nevoie de ajutor imediat?",
    contactanos: "Contactează-ne",
    contactSubtitle: "Ai un proiect în minte? Să vorbim! Suntem aici să te ajutăm să-ți realizezi ideile.",
    infoContacto: "Informații de Contact",
    telefono: "Telefon",
    email: "Email",
    ubicacion: "Locație",
    espana: "Spania",
    horario: "Program de Lucru",
    lunesViernes: "Luni - Vineri",
    sabados: "Sâmbete",
    domingos: "Duminici",
    cerrado: "Închis",
    enviamosMensaje: "Trimite-ne un Mesaj",
    mensajeExito: "Mesaj trimis cu succes! Te vom contacta în curând.",
    mensajeError: "A apărut o eroare la trimiterea mesajului. Te rugăm să încerci din nou.",
    nombreCompleto: "Nume Complet *",
    tuNombre: "Numele tău",
    emailPlaceholder: "emailul@tau.com",
    telefonoPlaceholder: "(0034)-647-857-388",
    servicioInteres: "Serviciul de Interes",
    seleccionaServicio: "Selectează un serviciu",
    obras: "Construcție și Demolare",
    pintura: "Vopsire și Finisaje",
    pavimentos: "Lucrări de Instalare Pereti și Podele",
    aislamiento: "Izolare și Placă de Gips",
    electricas: "Instalații Electrice",
    termicas: "Instalații Termice",
    otros: "Altele",
    obrasDesc: "Demolări, tencuială, plăci, structuri metalice, fundații și multe altele.",
    pinturaDesc: "Pereti, plăci, tapet, vopsire interioară și exterioară.",
    pavimentosDesc: "Beton, armare, gresie, granit, marmură, parchet și multe altele.",
    aislamientoDesc: "Placă de gips, structură metalică, izolare și plafoane false.",
    electricasDesc: "Iluminat, prize, întrerupătoare, proiectoare și multe altele.",
    termicasDesc: "Încălzire, radiatoare, cazane, hidrofoare și sisteme centrale.",
    mensaje: "Mesaj *",
    mensajePlaceholder: "Spune-ne despre proiectul tău...",
    enviando: "Trimitere...",
    enviarMensaje: "Trimite Mesaj",
    serviciosHeader: "Serviciile Noastre",
    serviciosDesc: "Efectuăm toate tipurile de lucrări de construcție în clădiri, anexe, piscine, garduri și porți. Finisaje exterioare și interioare, reparații și multe altele.",
    saberMas: "Află mai multe",
    verMenos: "Arată mai puțin",
    serviciosIncluidos: "Servicii Incluse:",
    presupuestoPersonalizado: "Ai nevoie de o ofertă personalizată?",
    contactaParaEvaluacion: "Contactează-ne pentru o evaluare gratuită a proiectului tău",
    enlacesRapidos: "Link-uri Rapide",
    sobreNosotros: "Despre Noi",
    galeria: "Galerie",
    contacto: "Contact",
    todosProyectos: "Toate Proiectele",
    cargando: "Se încarcă",
    verTodosProyectos: "Vezi Toate Proiectele",
    footerDerechos: "© 2018 D-PLACK CONSTRUCT. Toate drepturile rezervate.",
    politicaPrivacidad: "Politica de Confidențialitate",
    terminosServicio: "Termeni și Condiții",
    habilitarJS: "Trebuie să activezi JavaScript pentru a rula această aplicație.",
    // Gallery categories
    categoriaPergolas: "Pergole",
    categoriaPavimentos: "Pavaje",
    categoriaInterior: "Interior",
    categoriaExterior: "Exterior",
    categoriaAislamiento: "Izolare",
    proyecto: "Proiect",
    proyectoEjemplo: "Proiect de exemplu",
    galeriaDesc: "Explorează proiectele noastre cele mai remarcabile și descoperă calitatea muncii noastre.",
    // Gallery pagination and UI
    anterior: "Anterior",
    siguiente: "Următor",
    imagenNoDisponible: "Imagine indisponibilă",
    // Footer description
    footerDesc: "Specialiști în construcții, reabilitare și instalații. Lucrăm cu cele mai înalte standarde de securitate, calitate și profesionalism.",
    // Social media and accessibility
    seguirTwitter: "Urmărește-ne pe Twitter",
    seguirLinkedIn: "Urmărește-ne pe LinkedIn",
    politicaPrivacidadLabel: "Politica de Confidențialitate",
    terminosServicioLabel: "Termeni și Condiții",
    // Service details translations - Romanian
    obrasDetalle1: "Tencuială de gips",
    obrasDetalle2: "Perete gol (gips, gresie, faianță, glet, var, etc.)",
    obrasDetalle3: "Mozaic descoperit",
    obrasDetalle4: "Parchet îndepărtat, covor",
    obrasDetalle5: "Suprafețe de nisip diferite",
    obrasDetalle6: "Demolarea zidurilor de zidărie",
    obrasDetalle7: "Demolarea fundațiilor, elementelor de beton, zidurilor",
    obrasDetalle8: "Dezmembrarea sobelor de zidărie sau cărămidă",
    obrasDetalle9: "Structuri metalice îndepărtate",
    obrasDetalle10: "Borduri de beton demontate",
    pinturaDetalle1: "Glet gros, reparații, finisaj",
    pinturaDetalle2: "Finisaj glet",
    pinturaDetalle3: "Glet grunge",
    pinturaDetalle4: "Pregătirea suprafețelor pentru pictură",
    pinturaDetalle5: "Vopsea interioară spălabilă (două straturi și pereți cu o culoare)",
    pinturaDetalle6: "Structuri metalice vopsite",
    pinturaDetalle7: "Tâmplărie din lemn lăcuită și vernisată",
    pinturaDetalle8: "Zugraveala (glet, slefuit, amorsat, spălabil)",
    pinturaDetalle9: "Vopsea exterioară (cositor, grund, spălabil)",
    pinturaDetalle10: "Montaj joncțiuni PVC / aluminiu",
    pinturaDetalle11: "Praguri uși și ferestre",
    pinturaDetalle12: "Tâmplărie din lemn vopsită",
    pinturaDetalle13: "Fațadă pregătită pentru pictură exterioară",
    pinturaDetalle14: "Tapet aplicat",
    pinturaDetalle15: "Montaj panouri perete",
    pavimentosDetalle1: "Șapă de egalizare beton (funcție grosime)",
    pavimentosDetalle2: "Pregătire excavare",
    pavimentosDetalle3: "Șapă plutitoare (beton)",
    pavimentosDetalle4: "Armare cu plase metalice",
    pavimentosDetalle5: "Beton autonivelant pentru șapă",
    pavimentosDetalle6: "Cadru șapă 4 cm inclusă pregătirea",
    pavimentosDetalle7: "Revestiment granit",
    pavimentosDetalle8: "Galvanoplastie piatră (funcție piatră)",
    pavimentosDetalle9: "Montaj elemente liniare marmură, granit, travertin, etc.",
    pavimentosDetalle10: "Instalare rame ferestre granit, marmură, mozaic, etc.",
    pavimentosDetalle11: "Trepte nivelare cu granit, marmură, mozaic, piatră, etc.",
    pavimentosDetalle12: "Strat suport aglomerat, OSB, etc.",
    pavimentosDetalle13: "Instalare pardoseli lemn moale",
    pavimentosDetalle14: "Montaj covor",
    pavimentosDetalle15: "Montaj plintă covor",
    pavimentosDetalle16: "Montaj faianță (în funcție de dimensiune sau model)",
    pavimentosDetalle17: "Montaj plintă gresie",
    pavimentosDetalle18: "Revestiment plăci gresie piatră",
    pavimentosDetalle19: "Revestiment marmură",
    pavimentosDetalle20: "Pardoseli mozaic, marmură",
    pavimentosDetalle21: "Punere plintă mozaic, marmură",
    pavimentosDetalle22: "Reparație trepte mozaic",
    pavimentosDetalle23: "Montaj cărămidă Nevada",
    pavimentosDetalle24: "Montaj pardoseală clasică lemn masiv",
    pavimentosDetalle25: "Punere parchet",
    pavimentosDetalle26: "Instalare pardoseli laminat",
    pavimentosDetalle27: "Instalare MDF, PVC",
    pavimentosDetalle28: "Pardoseli lemn uzate",
    pavimentosDetalle29: "Parchet șlefuit și ceruit",
    aislamientoDetalle1: "Revestiment pereți cu plăci gips-carton pe structură metalică și izolație",
    aislamientoDetalle2: "Revestiment pereți gips-carton fără structură metalică",
    aislamientoDetalle3: "Instalare pereți despărțitori plăci gips-carton cu structură metalică pe față",
    aislamientoDetalle4: "Punere tavan pladur pe structură metalică",
    aislamientoDetalle5: "Instalare tavan suspendat + izolație lână",
    aislamientoDetalle6: "Schelă / placă gips",
    aislamientoDetalle7: "Izolație termică lână minerală",
    aislamientoDetalle8: "Diverse modele, arcade, schele",
    aislamientoDetalle9: "Tencuieli vopsite (bandă montată, curățată, șlefuită, grunduită, spălabilă)",
    aislamientoDetalle10: "Montaj tavane false cu lipire polistiren",
    electricasDetalle1: "Instalație electrică completă",
    electricasDetalle2: "Accesorii iluminat",
    electricasDetalle3: "Supliment instalație electrică (pentru fiecare plintă corp)",
    electricasDetalle4: "Montaj prize, întrerupătoare, spoturi",
    electricasDetalle5: "Instalare electrocasnice",
    termicasDetalle1: "Asamblare centrală și conexiune",
    termicasDetalle2: "Dezmembrare/asamblare centrală fără conexiune",
    termicasDetalle3: "Instalare și conexiune radiator",
    termicasDetalle4: "Radiator îndepărtat/montat fără conexiune",
    termicasDetalle5: "Instalare cazane lemn",
    termicasDetalle6: "Asamblare hidrofor",
    termicasDetalle7: "Montaj rezervor apă",
    termicasDetalle8: "Asamblare cabină duș",
    termicasDetalle9: "Instalare cadă clasică",
    termicasDetalle10: "Instalații alimentare apă",
    termicasDetalle11: "Sisteme canalizare (țevi asamblate). PVC (32, 40, 50 mm)",
    termicasDetalle12: "Baterie apă schimbată",
    termicasDetalle13: "Instalare baie modificată cupru",
    termicasDetalle14: "Instalare baie pexal modificată",
    termicasDetalle15: "Instalare bucătărie modificată cupru",
    termicasDetalle16: "Conexiune mașină spălat la canalizare",
    termicasDetalle17: "Instalare elemente sanitare (toaletă, chiuvetă)",
    termicasDetalle18: "Accesorii montaj baie și bucătărie (suporturi, oglinzi, rafturi)",
    termicasDetalle19: "Îndepărtare elemente sanitare"
  },
  el: {
    companyName: "D-PLACK CONSTRUCT",
    companySlogan: "Κατασκευή και Αποκατάσταση",
    navEmpresa: "Εταιρεία",
    navServicios: "Υπηρεσίες",
    navGaleria: "Γκαλερί",
    navContacto: "Επικοινωνία",
    phone: "(0034)-647-857-388",
    ctaPresupuesto: "Ζητήστε Προσφορά",
    ctaVerServicios: "Δείτε Υπηρεσίες",
    heroTitle1: "Κατασκευή",
    heroTitle2: "και Αποκατάσταση",
    heroSubtitle: "Η ποιότητα, ο επαγγελματισμός και η ικανοποίηση του πελάτη είναι οι θεμελιώδεις αρχές μας. Εργαζόμαστε με τα υψηλότερα πρότυπα ασφάλειας και ευθύνης.",
    featureSeguridad: "Εγγυημένη Ασφάλεια",
    featureCalidad: "Premium Ποιότητα",
    featureEco: "Φιλικό προς το Περιβάλλον",
    helpText: "Χρειάζεστε άμεση βοήθεια;",
    contactanos: "Επικοινωνήστε μαζί μας",
    contactSubtitle: "Έχετε ένα έργο στο μυαλό σας; Ας μιλήσουμε! Είμαστε εδώ για να σας βοηθήσουμε να πραγματοποιήσετε τις ιδέες σας.",
    infoContacto: "Πληροφορίες Επικοινωνίας",
    telefono: "Τηλέφωνο",
    email: "Email",
    ubicacion: "Τοποθεσία",
    espana: "Ισπανία",
    horario: "Ώρες Λειτουργίας",
    lunesViernes: "Δευτέρα - Παρασκευή",
    sabados: "Σάββατα",
    domingos: "Κυριακές",
    cerrado: "Κλειστά",
    enviamosMensaje: "Στείλτε μας ένα Μήνυμα",
    mensajeExito: "Μήνυμα αποστάλθηκε με επιτυχία! Θα επικοινωνήσουμε μαζί σας σύντομα.",
    mensajeError: "Προέκυψε σφάλμα κατά την αποστολή του μηνύματος. Παρακαλώ δοκιμάστε ξανά.",
    nombreCompleto: "Πλήρες Όνομα *",
    tuNombre: "Το όνομά σας",
    emailPlaceholder: "το@emailσας.com",
    telefonoPlaceholder: "(0034)-647-857-388",
    servicioInteres: "Υπηρεσία Ενδιαφέροντος",
    seleccionaServicio: "Επιλέξτε μια υπηρεσία",
    obras: "Κατασκευή και Κατεδάφιση",
    pintura: "Χρωματισμός και Τελική Επεξεργασία",
    pavimentos: "Εργασίες Εγκατάστασης Τοίχων και Δαπέδων",
    aislamiento: "Μόνωση και Γυψοσανίδες",
    electricas: "Ηλεκτρικές Εγκαταστάσεις",
    termicas: "Θερμικές Εγκαταστάσεις",
    otros: "Άλλα",
    obrasDesc: "Κατεδαφίσεις, γύψος, πλακάκια, μεταλλικές κατασκευές, θεμέλια και περισσότερα.",
    pinturaDesc: "Τοίχοι, πλακάκια, ταπετσαρία, εσωτερικός και εξωτερικός χρωματισμός.",
    pavimentosDesc: "Σκυρόδεμα, ενίσχυση, ψαμμίτης, γρανίτης, μάρμαρο, παρκέ και περισσότερα.",
    aislamientoDesc: "Γυψοσανίδες, μεταλλική κατασκευή, μόνωση και ψευδοροφές.",
    electricasDesc: "Φωτισμός, πρίζες, διακόπτες, προβολείς και περισσότερα.",
    termicasDesc: "Θέρμανση, καλοριφέρ, λέβητες, υδροφόροι και κεντρικά συστήματα.",
    mensaje: "Μήνυμα *",
    mensajePlaceholder: "Πείτε μας για το έργο σας...",
    enviando: "Αποστολή...",
    enviarMensaje: "Στείλτε Μήνυμα",
    serviciosHeader: "Οι Υπηρεσίες μας",
    serviciosDesc: "Εκτελούμε όλων των ειδών κατασκευαστικά έργα σε κτίρια, προσθήκες, πισίνες, φράχτες και πύλες. Εξωτερικές και εσωτερικές τελικές επεξεργασίες, επισκευές και περισσότερα.",
    saberMas: "Μάθετε περισσότερα",
    verMenos: "Δείτε λιγότερα",
    serviciosIncluidos: "Συμπεριλαμβανόμενες Υπηρεσίες:",
    presupuestoPersonalizado: "Χρειάζεστε μια εξατομικευμένη προσφορά;",
    contactaParaEvaluacion: "Επικοινωνήστε μαζί μας για μια δωρεάν αξιολόγηση του έργου σας",
    enlacesRapidos: "Γρήγοροι Σύνδεσμοι",
    sobreNosotros: "Σχετικά με εμάς",
    galeria: "Γκαλερί",
    contacto: "Επικοινωνία",
    todosProyectos: "Όλα τα Έργα",
    cargando: "Φόρτωση",
    verTodosProyectos: "Δείτε Όλα τα Έργα",
    footerDerechos: "© 2018 D-PLACK CONSTRUCT. Όλα τα δικαιώματα διατηρούνται.",
    politicaPrivacidad: "Πολιτική Απορρήτου",
    terminosServicio: "Όροι Υπηρεσίας",
    habilitarJS: "Πρέπει να ενεργοποιήσετε το JavaScript για να εκτελέσετε αυτή την εφαρμογή.",
    // Gallery categories
    categoriaPergolas: "Πέργκολες",
    categoriaPavimentos: "Επενδύσεις Δαπέδων",
    categoriaInterior: "Εσωτερικός Χώρος",
    categoriaExterior: "Εξωτερικός Χώρος",
    categoriaAislamiento: "Μόνωση",
    proyecto: "Έργο",
    proyectoEjemplo: "Παράδειγμα Έργου",
    galeriaDesc: "Εξερευνήστε τα πιο εξαιρετικά έργα μας και ανακαλύψτε την ποιότητα της εργασίας μας.",
    // Gallery pagination and UI
    anterior: "Προηγούμενο",
    siguiente: "Επόμενο",
    imagenNoDisponible: "Η εικόνα δεν είναι διαθέσιμη",
    // Footer description
    footerDesc: "Ειδικοί σε κατασκευές, αποκατάσταση και εγκαταστάσεις. Εργαζόμαστε με τα υψηλότερα πρότυπα ασφαλείας, ποιότητας και επαγγελματισμού.",
    // Social media and accessibility
    seguirTwitter: "Ακολουθήστε μας στο Twitter",
    seguirLinkedIn: "Ακολουθήστε μας στο LinkedIn",
    politicaPrivacidadLabel: "Πολιτική Απορρήτου",
    terminosServicioLabel: "Όροι Υπηρεσίας",
    // Service details translations - Greek
    obrasDetalle1: "Γύψος",
    obrasDetalle2: "Γυμνός τοίχος (γύψος, ψαμμίτης, πλακάκι, glet, ασβέστης, κλπ.)",
    obrasDetalle3: "Ακάλυπτο μωσαϊκό",
    obrasDetalle4: "Αφαιρεμένο παρκέ, χαλί",
    obrasDetalle5: "Διαφορετικές επιφάνειες άμμου",
    obrasDetalle6: "Κατεδάφιση τοίχων τοιχοποιίας",
    obrasDetalle7: "Κατεδάφιση θεμελίων, στοιχείων σκυροδέματος, τοίχων",
    obrasDetalle8: "Αποσυναρμολόγηση σόμπες τοιχοποιίας ή τούβλου",
    obrasDetalle9: "Αφαιρεμένες μεταλλικές κατασκευές",
    obrasDetalle10: "Αποσυναρμολογημένες κορνίζες σκυροδέματος",
    pinturaDetalle1: "Παχύ glet, επισκευές, φινίρισμα",
    pinturaDetalle2: "Φινίρισμα glet",
    pinturaDetalle3: "Grunge glet",
    pinturaDetalle4: "Προετοιμασία επιφανειών για βαφή",
    pinturaDetalle5: "Πλύσιμη εσωτερική βαφή (δύο στρώματα και τοίχοι με ένα χρώμα)",
    pinturaDetalle6: "Βαμμένες μεταλλικές κατασκευές",
    pinturaDetalle7: "Βερνικωμένη και βερνικωμένη ξύλινη ξυλουργική",
    pinturaDetalle8: "Zugraveala (glet, slefuit, amorsat, πλύσιμο)",
    pinturaDetalle9: "Εξωτερική βαφή (κασσίτερος, αστάρι, πλύσιμο)",
    pinturaDetalle10: "Συναρμολόγηση αρμών PVC / αλουμινίου",
    pinturaDetalle11: "Παραθυρόφυλλα και παραθυρόφυλλα",
    pinturaDetalle12: "Βαμμένη ξύλινη ξυλουργική",
    pinturaDetalle13: "Πρόσοψη προετοιμασμένη για εξωτερική βαφή",
    pinturaDetalle14: "Εφαρμοσμένη ταπετσαρία",
    pinturaDetalle15: "Συναρμολόγηση τοιχωμάτων",
    pavimentosDetalle1: "Εξίσωση σκυροδέματος (συνάρτηση πάχους)",
    pavimentosDetalle2: "Προετοιμασία εκσκαφής",
    pavimentosDetalle3: "Πλωτή εξίσωση (σκυρόδεμα)",
    pavimentosDetalle4: "Ενίσχυση με μεταλλικά πλέγματα",
    pavimentosDetalle5: "Αυτοεξισωτικό σκυρόδεμα για εξίσωση",
    pavimentosDetalle6: "Κάδρο εξίσωσης 4 cm συμπεριλαμβανομένης της προετοιμασίας",
    pavimentosDetalle7: "Επένδυση γρανίτη",
    pavimentosDetalle8: "Γαλβανόπλαστικη πέτρα (συνάρτηση πέτρας)",
    pavimentosDetalle9: "Συναρμολόγηση γραμμικών στοιχείων μαρμάρου, γρανίτη, τραβερτίνου, κλπ.",
    pavimentosDetalle10: "Εγκατάσταση κουφωμάτων παραθύρων γρανίτη, μαρμάρου, μωσαϊκού, κλπ.",
    pavimentosDetalle11: "Βήματα εξίσωσης με γρανίτη, μάρμαρο, μωσαϊκό, πέτρα, κλπ.",
    pavimentosDetalle12: "Στρώμα στήριξης συμπαγούς, OSB, κλπ.",
    pavimentosDetalle13: "Εγκατάσταση δαπέδων μαλακού ξύλου",
    pavimentosDetalle14: "Συναρμολόγηση χαλιού",
    pavimentosDetalle15: "Συναρμολόγηση σοκέ χαλιού",
    pavimentosDetalle16: "Συναρμολόγηση πλακιδίων (ανάλογα με το μέγεθος ή το μοντέλο)",
    pavimentosDetalle17: "Συναρμολόγηση σοκέ ψαμμίτη",
    pavimentosDetalle18: "Επένδυση πλακιδίων ψαμμίτη πέτρας",
    pavimentosDetalle19: "Επένδυση μαρμάρου",
    pavimentosDetalle20: "Δάπεδα μωσαϊκού, μαρμάρου",
    pavimentosDetalle21: "Τοποθέτηση σοκέ μωσαϊκού, μαρμάρου",
    pavimentosDetalle22: "Επισκευή σκαλοπατιών μωσαϊκού",
    pavimentosDetalle23: "Συναρμολόγηση τούβλου Nevada",
    pavimentosDetalle24: "Συναρμολόγηση κλασικού δαπέδου στερεού ξύλου",
    pavimentosDetalle25: "Τοποθέτηση παρκέ",
    pavimentosDetalle26: "Εγκατάσταση δαπέδων laminate",
    pavimentosDetalle27: "Εγκατάσταση MDF, PVC",
    pavimentosDetalle28: "Φθαρμένα ξύλινα δάπεδα",
    pavimentosDetalle29: "Γυαλισμένο και κερισμένο παρκέ",
    aislamientoDetalle1: "Επένδυση τοίχων με πλάκες γύψου-χαρτονιού σε μεταλλική κατασκευή και μόνωση",
    aislamientoDetalle2: "Επένδυση τοίχων γύψου-χαρτονιού χωρίς μεταλλική κατασκευή",
    aislamientoDetalle3: "Εγκατάσταση χωρισμάτων πλακών γύψου-χαρτονιού με μεταλλική κατασκευή ανά πλευρά",
    aislamientoDetalle4: "Τοποθέτηση οροφής pladur σε μεταλλική κατασκευή",
    aislamientoDetalle5: "Εγκατάσταση κρεμαστής οροφής + μόνωση μαλλιού",
    aislamientoDetalle6: "Σκαλωσιά / πλάκα γύψου",
    aislamientoDetalle7: "Θερμική μόνωση ορυκτού μαλλιού",
    aislamientoDetalle8: "Διάφορα μοντέλα, αψίδες, σκαλωσιές",
    aislamientoDetalle9: "Βαμμένες επενδύσεις (τοποθετημένη ταινία, σκληρυμένη, γυαλισμένη, ασταρωμένη, πλύσιμη)",
    aislamientoDetalle10: "Συναρμολόγηση ψευδοροφών με κόλληση πολυστυρενίου",
    electricasDetalle1: "Πλήρης ηλεκτρική εγκατάσταση",
    electricasDetalle2: "Αξεσουάρ φωτισμού",
    electricasDetalle3: "Πρόσθετο ηλεκτρικής εγκατάστασης (για κάθε σοκέ σώματος)",
    electricasDetalle4: "Συναρμολόγηση σοκέ, διακοπτών, προβολέων",
    electricasDetalle5: "Εγκατάσταση ηλεκτρικών συσκευών",
    termicasDetalle1: "Κεντρική συναρμολόγηση και σύνδεση",
    termicasDetalle2: "Αποσυναρμολόγηση/συναρμολόγηση κεντρικής μονάδας χωρίς σύνδεση",
    termicasDetalle3: "Εγκατάσταση και σύνδεση καλοριφέρ",
    termicasDetalle4: "Καλοριφέρ αφαιρεμένο/συναρμολογημένο χωρίς σύνδεση",
    termicasDetalle5: "Εγκατάσταση λέβητες ξύλου",
    termicasDetalle6: "Συναρμολόγηση υδροφόρου",
    termicasDetalle7: "Συναρμολόγηση δεξαμενής νερού",
    termicasDetalle8: "Συναρμολόγηση καμπίνας ντους",
    termicasDetalle9: "Εγκατάσταση κλασικής μπανιέρας",
    termicasDetalle10: "Εγκαταστάσεις παροχής νερού",
    termicasDetalle11: "Συστήματα αποχέτευσης (συναρμολογημένοι σωλήνες). PVC (32, 40, 50 mm)",
    termicasDetalle12: "Μπαταρία νερού αλλαγμένη",
    termicasDetalle13: "Εγκατάσταση μπάνιου τροποποιημένη σε χαλκό",
    termicasDetalle14: "Εγκατάσταση μπάνιου pexal τροποποιημένη",
    termicasDetalle15: "Εγκατάσταση κουζίνας τροποποιημένη σε χαλκό",
    termicasDetalle16: "Σύνδεση πλυντηρίου ρούχων στην αποχέτευση",
    termicasDetalle17: "Εγκατάσταση υγειονομικών στοιχείων (τουαλέτα, νιπτήρας)",
    termicasDetalle18: "Αξεσουάρ συναρμολόγησης μπάνιου και κουζίνας (στηρίγματα, καθρέφτες, ράφια)",
    termicasDetalle19: "Αφαίρεση υγειονομικών στοιχείων"
  },
  it: {
    companyName: "D-PLACK CONSTRUCT",
    companySlogan: "Costruzione e Riqualificazione",
    navEmpresa: "Azienda",
    navServicios: "Servizi",
    navGaleria: "Galleria",
    navContacto: "Contatto",
    phone: "(0034)-647-857-388",
    ctaPresupuesto: "Richiedi Preventivo",
    ctaVerServicios: "Vedi Servizi",
    heroTitle1: "Costruzione",
    heroTitle2: "e Riqualificazione",
    heroSubtitle: "Qualità, professionalità e soddisfazione del cliente sono i nostri principi fondamentali. Lavoriamo con i più alti standard di sicurezza e responsabilità.",
    featureSeguridad: "Sicurezza Garantita",
    featureCalidad: "Qualità Premium",
    featureEco: "Eco-Friendly",
    helpText: "Hai bisogno di aiuto immediato?",
    contactanos: "Contattaci",
    contactSubtitle: "Hai un progetto in mente? Parliamone! Siamo qui per aiutarti a realizzare le tue idee.",
    infoContacto: "Informazioni di Contatto",
    telefono: "Telefono",
    email: "Email",
    ubicacion: "Posizione",
    espana: "Spagna",
    horario: "Orari di Lavoro",
    lunesViernes: "Lunedì - Venerdì",
    sabados: "Sabati",
    domingos: "Domeniche",
    cerrado: "Chiuso",
    enviamosMensaje: "Inviaci un Messaggio",
    mensajeExito: "Messaggio inviato con successo! Ti contatteremo presto.",
    mensajeError: "Si è verificato un errore nell'invio del messaggio. Riprova.",
    nombreCompleto: "Nome Completo *",
    tuNombre: "Il tuo nome",
    emailPlaceholder: "tuo@email.com",
    telefonoPlaceholder: "(0034)-647-857-388",
    servicioInteres: "Servizio di Interesse",
    seleccionaServicio: "Seleziona un servizio",
    obras: "Costruzione e Demolizione",
    pintura: "Pittura e Finiture",
    pavimentos: "Lavori di Installazione Pareti e Pavimenti",
    aislamiento: "Isolamento e Cartongesso",
    electricas: "Installazioni Elettriche",
    termicas: "Installazioni Termiche",
    otros: "Altri",
    obrasDesc: "Demolizioni, intonaco, piastrelle, strutture metalliche, fondazioni e altro.",
    pinturaDesc: "Pareti, piastrelle, carta da parati, pittura interna ed esterna.",
    pavimentosDesc: "Calcestruzzo, rinforzo, arenaria, granito, marmo, parquet e altro.",
    aislamientoDesc: "Cartongesso, struttura metallica, isolamento e controsoffitti.",
    electricasDesc: "Illuminazione, prese, interruttori, proiettori e altro.",
    termicasDesc: "Riscaldamento, radiatori, caldaie, idrofori e sistemi centrali.",
    mensaje: "Messaggio *",
    mensajePlaceholder: "Parlaci del tuo progetto...",
    enviando: "Invio...",
    enviarMensaje: "Invia Messaggio",
    serviciosHeader: "I Nostri Servizi",
    serviciosDesc: "Eseguiamo tutti i tipi di lavori di costruzione in edifici, annessi, piscine, recinzioni e cancelli. Finiture esterne e interne, riparazioni e altro.",
    saberMas: "Scopri di più",
    verMenos: "Mostra meno",
    serviciosIncluidos: "Servizi Inclusi:",
    presupuestoPersonalizado: "Hai bisogno di un preventivo personalizzato?",
    contactaParaEvaluacion: "Contattaci per una valutazione gratuita del tuo progetto",
    enlacesRapidos: "Link Rapidi",
    sobreNosotros: "Chi Siamo",
    galeria: "Galleria",
    contacto: "Contatto",
    todosProyectos: "Tutti i Progetti",
    cargando: "Caricamento",
    verTodosProyectos: "Vedi Tutti i Progetti",
    footerDerechos: "© 2018 D-PLACK CONSTRUCT. Tutti i diritti riservati.",
    politicaPrivacidad: "Politica sulla Privacy",
    terminosServicio: "Termini di Servizio",
    habilitarJS: "Devi abilitare JavaScript per eseguire questa applicazione.",
    // Gallery categories
    categoriaPergolas: "Pergole",
    categoriaPavimentos: "Pavimentazioni",
    categoriaInterior: "Interni",
    categoriaExterior: "Esterni",
    categoriaAislamiento: "Isolamento",
    proyecto: "Progetto",
    proyectoEjemplo: "Progetto di esempio",
    galeriaDesc: "Esplora i nostri progetti più eccezionali e scopri la qualità del nostro lavoro.",
    // Gallery pagination and UI
    anterior: "Precedente",
    siguiente: "Successivo",
    imagenNoDisponible: "Immagine non disponibile",
    // Footer description
    footerDesc: "Specialisti in costruzioni, riabilitazione e installazioni. Lavoriamo con i più alti standard di sicurezza, qualità e professionalità.",
    // Social media and accessibility
    seguirTwitter: "Seguici su Twitter",
    seguirLinkedIn: "Seguici su LinkedIn",
    politicaPrivacidadLabel: "Informativa sulla Privacy",
    terminosServicioLabel: "Termini di Servizio",
    // Service details translations - Italian
    obrasDetalle1: "Intonaco di gesso",
    obrasDetalle2: "Muro nudo (gesso, arenaria, piastrella, glet, calce, ecc.)",
    obrasDetalle3: "Mosaico scoperto",
    obrasDetalle4: "Parquet rimosso, tappeto",
    obrasDetalle5: "Superfici di sabbia diverse",
    obrasDetalle6: "Demolizione di muri in muratura",
    obrasDetalle7: "Demolizione di fondazioni, elementi in cemento, muri",
    obrasDetalle8: "Smontaggio di stufe in muratura o mattoni",
    obrasDetalle9: "Strutture metalliche rimosse",
    obrasDetalle10: "Cordoli in cemento smontati",
    pinturaDetalle1: "Glet spesso, riparazioni, finitura",
    pinturaDetalle2: "Finitura glet",
    pinturaDetalle3: "Glet grunge",
    pinturaDetalle4: "Preparazione superfici per pittura",
    pinturaDetalle5: "Pittura interna lavabile (due mani e pareti con un colore)",
    pinturaDetalle6: "Strutture metalliche dipinte",
    pinturaDetalle7: "Falegnameria in legno laccata e verniciata",
    pinturaDetalle8: "Zugraveala (glet, slefuit, amorsat, lavabile)",
    pinturaDetalle9: "Pittura esterna (stagno, primer, lavabile)",
    pinturaDetalle10: "Montaggio giunti PVC / alluminio",
    pinturaDetalle11: "Soglie di porte e finestre",
    pinturaDetalle12: "Falegnameria in legno tinta",
    pinturaDetalle13: "Facciata preparata per pittura esterna",
    pinturaDetalle14: "Carta da parati applicata",
    pinturaDetalle15: "Montaggio pannelli murali",
    pavimentosDetalle1: "Massetto di livellamento cemento (funzione spessore)",
    pavimentosDetalle2: "Preparazione scavo",
    pavimentosDetalle3: "Massetto galleggiante (cemento)",
    pavimentosDetalle4: "Rinforzo con reti metalliche",
    pavimentosDetalle5: "Cemento autolivellante per massetto",
    pavimentosDetalle6: "Telaio massetto 4 cm inclusa preparazione",
    pavimentosDetalle7: "Rivestimento granito",
    pavimentosDetalle8: "Galvanoplastia pietra (funzione pietra)",
    pavimentosDetalle9: "Montaggio elementi lineari marmo, granito, travertino, ecc.",
    pavimentosDetalle10: "Installazione telai finestre granito, marmo, mosaico, ecc.",
    pavimentosDetalle11: "Gradini di livellamento con granito, marmo, mosaico, pietra, ecc.",
    pavimentosDetalle12: "Strato di supporto agglomerato, OSB, ecc.",
    pavimentosDetalle13: "Installazione pavimenti legno tenero",
    pavimentosDetalle14: "Montaggio tappeto",
    pavimentosDetalle15: "Montaggio battiscopa tappeto",
    pavimentosDetalle16: "Montaggio piastrelle (a seconda di dimensione o modello)",
    pavimentosDetalle17: "Montaggio battiscopa arenaria",
    pavimentosDetalle18: "Rivestimento piastrelle pietra arenaria",
    pavimentosDetalle19: "Rivestimento marmo",
    pavimentosDetalle20: "Pavimenti mosaico, marmo",
    pavimentosDetalle21: "Posizionamento battiscopa mosaico, marmo",
    pavimentosDetalle22: "Riparazione gradini mosaico",
    pavimentosDetalle23: "Montaggio mattone Nevada",
    pavimentosDetalle24: "Montaggio pavimento classico legno massello",
    pavimentosDetalle25: "Posizionamento parquet",
    pavimentosDetalle26: "Installazione pavimenti laminati",
    pavimentosDetalle27: "Installazione MDF, PVC",
    pavimentosDetalle28: "Pavimenti legno usurati",
    pavimentosDetalle29: "Parquet lucidato e cerato",
    aislamientoDetalle1: "Rivestimento pareti con pannelli cartongesso su struttura metallica e isolante",
    aislamientoDetalle2: "Rivestimento pareti cartongesso senza struttura metallica",
    aislamientoDetalle3: "Installazione tramezzi pannelli cartongesso con struttura metallica per faccia",
    aislamientoDetalle4: "Posizionamento soffitto pladur su struttura metallica",
    aislamientoDetalle5: "Installazione soffitto sospeso + isolamento lana",
    aislamientoDetalle6: "Ponteggio / pannello gesso",
    aislamientoDetalle7: "Isolamento termico lana minerale",
    aislamientoDetalle8: "Vari modelli, arcate, ponteggi",
    aislamientoDetalle9: "Intonaci dipinti (nastro montato, curato, lucidato, primerato, lavabile)",
    aislamientoDetalle10: "Montaggio controsoffitti con incollaggio polistirene",
    electricasDetalle1: "Installazione elettrica completa",
    electricasDetalle2: "Accessori illuminazione",
    electricasDetalle3: "Supplemento installazione elettrica (per ogni battiscopa corpo)",
    electricasDetalle4: "Montaggio prese, interruttori, faretti",
    electricasDetalle5: "Installazione elettrodomestici",
    termicasDetalle1: "Assemblaggio centrale e connessione",
    termicasDetalle2: "Smontaggio/assemblaggio unità centrale senza connessione",
    termicasDetalle3: "Installazione e connessione radiatore",
    termicasDetalle4: "Radiatore rimosso/montato senza connessione",
    termicasDetalle5: "Installazione caldaie legna",
    termicasDetalle6: "Assemblaggio idroforo",
    termicasDetalle7: "Montaggio serbatoio acqua",
    termicasDetalle8: "Assemblaggio cabina doccia",
    termicasDetalle9: "Installazione vasca classica",
    termicasDetalle10: "Installazioni approvvigionamento acqua",
    termicasDetalle11: "Sistemi fognari (tubi assemblati). PVC (32, 40, 50 mm)",
    termicasDetalle12: "Batteria acqua cambiata",
    termicasDetalle13: "Installazione bagno modificata rame",
    termicasDetalle14: "Installazione bagno pexal modificata",
    termicasDetalle15: "Installazione cucina modificata rame",
    termicasDetalle16: "Connessione lavatrice alla fognatura",
    termicasDetalle17: "Installazione elementi sanitari (water, lavandino)",
    termicasDetalle18: "Accessori montaggio bagno e cucina (supporti, specchi, scaffali)",
    termicasDetalle19: "Rimozione elementi sanitari"
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  supportedLanguages: typeof SUPPORTED_LANGUAGES;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Language detection functions
const detectUserPreference = (): LanguageCode | null => {
  try {
    // Check localStorage first
    const saved = localStorage.getItem('extensoapps-language');
    if (saved && saved in SUPPORTED_LANGUAGES) {
      return saved as LanguageCode;
    }

    // Check cookies as fallback
    const cookies = document.cookie.split(';');
    const languageCookie = cookies.find(cookie => cookie.trim().startsWith('preferred-language='));
    if (languageCookie) {
      const language = languageCookie.split('=')[1];
      if (language in SUPPORTED_LANGUAGES) {
        return language as LanguageCode;
      }
    }
  } catch (error) {
    console.warn('Could not read from localStorage or cookies:', error);
  }
  return null;
};

const detectCountryFromIP = async (): Promise<LanguageCode | null> => {
  try {
    const response = await fetch('https://ipapi.co/json/');
    const data = await response.json();
    const countryCode = data.country_code;
    return COUNTRY_TO_LANGUAGE[countryCode] || null;
  } catch (error) {
    console.warn('Could not detect country from IP:', error);
    return null;
  }
};

const detectBrowserLanguage = (): LanguageCode => {
  if (typeof navigator === 'undefined') return 'es';
  
  const browserLang = navigator.language.split('-')[0];
  return (browserLang in SUPPORTED_LANGUAGES ? browserLang : 'es') as LanguageCode;
};

const detectLanguage = async (): Promise<LanguageCode> => {
  // Tier 1: User Preference (localStorage or cookies)
  const userPref = detectUserPreference();
  if (userPref) return userPref;

  // Tier 2: IP-based detection
  const ipLang = await detectCountryFromIP();
  if (ipLang) return ipLang;

  // Tier 3: Browser language
  return detectBrowserLanguage();
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('es');
  const [isLoading, setIsLoading] = useState(true);
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    const initializeLanguage = async () => {
      if (isInitialized) return;
      
      const detectedLang = await detectLanguage();
      setLanguageState(detectedLang);
      setIsLoading(false);
      setIsInitialized(true);
    };

    initializeLanguage();
  }, [isInitialized]);

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      // Save to localStorage
      localStorage.setItem('extensoapps-language', lang);
      
      // Save to cookies for middleware access
      document.cookie = `preferred-language=${lang}; max-age=${60 * 60 * 24 * 365}; path=/; samesite=lax`;
    } catch (error) {
      console.warn('Could not save language preference:', error);
    }
  }, []);

  const t = useCallback((key: string): string => {
    const currentTranslations = translations[language];
    return currentTranslations[key as keyof typeof currentTranslations] || 
           translations.es[key as keyof typeof translations.es] || 
           key;
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t,
    supportedLanguages: SUPPORTED_LANGUAGES
  }), [language, setLanguage, t]);

  if (isLoading) {
    return <div className="min-h-screen flex items-center justify-center">Loading...</div>;
  }

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}; 